#!/bin/bash

username="bastien"
cd "/home/$username"

# Add fish to repo
echo "deb http://download.opensuse.org/repositories/shells:/fish:/release:/2/Debian_8.0/ /" > /etc/apt/sources.list.d/fish.list 
wget http://download.opensuse.org/repositories/shells:fish:release:2/Debian_8.0/Release.key
apt-key add - < Release.key

apt-get update
apt-get upgrade
apt-get install -y aptitude git autoconf automake curl emacs25 terminator fish sudo make build-essential libssl-dev libreadline-dev zlib1g-dev silversearcher-ag htop xsel acpi libssl1.0-dev
chsh "$username" -s /usr/bin/fish

# Build dep for Ruby
aptitude install bison libyaml-dev libreadline6-dev zlib1g-dev libncurses5-dev libffi-dev libgdbm3 libgdbm-dev

# Install haxe
echo "deb http://httpredir.debian.org/debian unstable main contrib non-free" >> /etc/apt/sources.list
echo "Package: *
Pin: release a=unstable
Pin-Priority: 100

Package: haxe neko libneko*
Pin: release a=unstable
Pin-Priority: 999" > /etc/apt/preferences.d/haxe_unstable
apt-get update
apt-get install haxe -y

# Build dep for Erlang
aptitude build-dep erlang -y

adduser "$username" sudo
